### ISSUE TITLE
DBSCAN的参数是怎么选出来的

### ISSUE THREAD

**Issue by Tangzy7** [FesonX/cn-text-classifier#2]
eps和min_samples是怎么选出来的，有什么好的选取办法吗

**Comment by FesonX** [comment]
这个跟样本本身的特性有较大关系，我用了比较取巧的方式来选取，类似二分法，先放大精确度，比如最开始 eps 用 0.1 步进，固定min_samples（因为聚类数据不是很多，可以放心用一个循环遍历，把结果图像和数据保存下来），从图像分析哪个与预期接近，单独拎出来进行0.05的步进，逐步缩小范围来确定

**Comment by FesonX** [comment]
> eps和min_samples是怎么选出来的，有什么好的选取办法吗

这个跟样本本身的特性有较大关系，我用了比较取巧的方式来选取，类似二分法，先放大精确度，比如最开始 eps 用 0.1 步进，固定min_samples（因为聚类数据不是很多，可以放心用一个循环遍历，把结果图像和数据保存下来），从图像分析哪个与预期接近，单独拎出来进行0.05的步进，逐步缩小范围来确定
